global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: my_app
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:9090

  - job_name: node_exporter
    static_configs:
      - targets:
        - node_exporter:9100
