version: "3.9"

services:
  app:
    image: my_app:latest
    container_name: app_container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./settings/prometheus:/etc/prometheus
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./settings/grafana:/etc/grafana/provisioning/datasources
    networks:
      - monitoring
    depends_on:
      - prometheus


networks:
  monitoring:

